language: generic 

sudo: required
services:
  - docker
  
before_install:
  - docker build -t ekolmakov/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true ekolmakov/docker-react npm run test
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  # см. скриншот aws
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-701836065776"
  bucket_path: docker
  on: 
    branch: master
    
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY
    