FROM node:alpine

WORKDIR /usr/local/app/

COPY package.json .

# install step
RUN npm install

# What we will update outside container
RUN npm update

COPY . .

CMD ["npm","run","start"]

CMD ["npm", "start"]
